main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # LANDING, SIGNUP & ABOUT ===============
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('accounts/signup', views.signup, name='signup'),
    
    # TASK ===============
    path('tasks/', views.tasks, name='tasks'),
    path('tasks/<int:task_id>/', views.task_show, name='task_show'),
    path('tasks/<int:task_id>/edit/', views.task_edit, name='task_edit'),
    path('tasks/<int:task_id>/delete/', views.task_delete, name='task_delete'),
    path('tasks/<int:task_id>/complete/', views.task_complete, name='task_complete'),
    path('tasks/<int:task_id>/uncomplete/', views.task_uncomplete, name='task_uncomplete'),

    # TIME ===============
    path('time/add/', views.time_add, name='time_add'),
    path('time/<int:time_id>/edit/', views.time_edit, name='time_edit'),
    path('time/<int:time_id>/delete/', views.time_delete, name='time_delete'),
    
    # PROFILE & PROJECT =============== 
    path('profile/<int:profile_id>/', views.profile_show, name='profile_show'),
    path('profile/<int:profile_id>/edit/', views.profile_edit, name='profile_edit'),
    path('profile/<int:profile_id>/delete/', views.profile_delete, name='profile_delete'),

    # PROFILE & PROJECT ===============
    path('projects/', views.projects, name='projects'),
    path('projects/<int:project_id>/', views.project_show, name='project_show'),
    path('projects/<int:project_id>/edit/', views.project_edit, name='project_edit'),
    path('projects/<int:project_id>/delete/', views.project_delete, name='project_delete'),

    # NOTES ===============
    path('note/<int:task_id>/add/', views.note_add, name='note_add'),
    path('note/<int:note_id>/edit/', views.note_edit, name='note_edit'),
    path('note/<int:note_id>/delete/', views.note_delete, name='note_delete'),

]

tasker_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError
from django.db.models import Q, F
from datetime import datetime, date

from taggit.managers import TaggableManager


# MODEL PROFILE ====================================
class Profile(models.Model):
    name = models.CharField(max_length=50, blank=True)
    dateJoined = models.DateField(auto_now=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=150)
    image = models.URLField(max_length=250, default="https://semantic-ui.com/images/avatar/large/steve.jpg")

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()



# MODEL PROJECT ====================================
class Project(models.Model):
    projectName = models.CharField(max_length=50)
    startDate = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(Profile, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.projectName
  
    class Meta:
        ordering = ['-startDate']



# MODEL TASK ====================================
class Task(models.Model):
    taskName = models.CharField(max_length=50)
    createdDate = models.DateField(auto_now_add=True)
    taskComplete = models.BooleanField(auto_created=False)
    taskCompletedDate = models.DateField(null=True, blank=True)
    creator = models.ForeignKey(Profile, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.taskName

    class Meta:
        ordering = ['project', 'createdDate']



# MODEL NOTES ====================================
class Note(models.Model):
    note = models.TextField()
    noteCreatedDate = models.DateField(auto_now=True)
    creator = models.ForeignKey(Profile, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.note)



# MODEL TIME ====================================
class Time(models.Model):
    date = models.DateField()
    startTime = models.TimeField()
    endTime = models.TimeField()
    tags = TaggableManager()
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def clean(self):
        if self.startTime > self.endTime:
            raise ValidationError('Start time should be before end time')
        return super().clean()

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=Q(startTime__lte=F('endTime')),
                name='startTime_before_endTime'
            )
        ]

    def getDuration(self):
        duration = datetime.combine(date.min, self.endTime) - datetime.combine(date.min, self.startTime)
        return duration
    
    def getTags(self):
        tags = []
        for tag in self.tags.all():
            tags.append(str(tag))
        return ', '.join(tags)

    def __str__(self):
        return str(self.date)

main_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Task, Project, Profile, Note, Time
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# TASK ===============
class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = [ 'taskName', 'project' ]



# PROJECT ===============
class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = [ 'projectName' ]



# PROFILE ===============
class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name','email','image']



# NOTES ===============
class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = [ 'note' ]



# USERCREATION ===============
class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=25)
    name = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=150)

    class Meta:
        model = User
        fields = ('username', 'email', 'name', 'password1', 'password2')


# TIME FORM ===============
class TimeForm(ModelForm):
    class Meta:
        model = Time
        fields = "__all__"

main_app/views.py
# EXTERNAL IMPORTS DJANGO -----------------------------------
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# EXTERNAL IMPORTS OTHER -----------------------------------
from taggit.models import Tag
from datetime import date, timedelta
import datetime

# INTERNAL IMPORTS -----------------------------------
from .models import Profile, Project, Task, Note, Time
from .forms import TaskForm, ProjectForm, ProfileForm, SignUpForm, NoteForm, TimeForm





# ADMIN ====================================
# --- LANDING PAGE ROUTE ---
def home(request):
  return render(request, 'home.html')

# --- ABOUT TASKER & AUTHOR ---
def about(request):
    return render( request, 'about.html' )

# --- SIGNUP NEW USER & CREATE NEW PROFILE WITH RECIEVER IN MODEL
def signup(request):
  error_message = ''
  print(request.POST)
  form = SignUpForm(request.POST)
  if form.is_valid():
    user = form.save()
    user.refresh_from_db()
    user.profile.email = form.cleaned_data.get('email')
    user.profile.name = form.cleaned_data.get('name')
    user.save()
    login(request, user)
    return redirect('projects')
  else:
    # error_message = 'Invalid sign up - try again'
    form = SignUpForm()
  context = {'form': form, 'error_message': error_message }
  return render( request, 'registration/signup.html', context )


# TASKS ====================================
# --- SHOW ALL TASKS & NEW TASK ROUTE ---
@login_required
def tasks(request):
  if request.method == 'POST':
    taskName = request.POST.get('taskName')
    project = Project.objects.get(id=request.POST.get('project'))
    creator = Profile.objects.get(id=request.user.id)
    new_task = Task(taskName=taskName, creator=creator, project=project)
    new_task.taskComplete = False
    new_task.save()
    return redirect('tasks')
  tasks = Task.objects.filter(creator=request.user.profile, taskComplete=False)
  projects = Project.objects.filter(creator=request.user.profile)
  creator = Profile.objects.get(id=request.user.id)
  priorTasks = []
  tasklist = Task.objects.filter(creator=request.user.profile)
  for task in tasklist:
    if task.createdDate < date.today() - timedelta(days=1):
      priorTasks.append(task)
  task_form = TaskForm()
  context = { 'tasks': tasks, 'task_form': task_form, 'projects': projects, 'priorTasks': priorTasks }
  return render(request, 'tasks/index.html', context )

# --- SHOW TASK ROUTE ---
@login_required
def task_show(request, task_id):
  task = Task.objects.get(id=task_id)
  notes = task.note_set.all()
  times = Time.objects.filter(task=task_id)
  durations = []
  tags = []
  for time in times:
    durations.append(time.getDuration())
    tags.append(time.getTags())
  timeDates = list(zip(times, tags))
  totalTime = sum(durations, datetime.timedelta())
  project = Project.objects.get(task=task_id)
  context = {'task': task, "project": project, 'notes': notes, 'times': times, 'totalTime': totalTime, "timeDates": timeDates}
  return render(request, 'tasks/show.html', context)

# --- EDIT TASK ROUTE ---
@login_required
def task_edit(request, task_id):
  task = Task.objects.get(id=task_id)
  if request.method == 'POST':
    if request.user.id == task.creator.user.id:
      task_form = TaskForm(request.POST, instance=task)
      if task_form.is_valid():
        task_form.save()
        return redirect('task_show', task_id=task_id)
    else:
      return redirect('task_show', task_id=task_id)
  else:
    task_form = TaskForm(instance=task)
  projects = Project.objects.filter(creator=request.user.profile)
  context = { 'task': task, 'task_form': task_form, 'projects': projects }
  return render(request, 'tasks/edit.html', context)

# --- COMPLETE TASK ROUTE ---
@login_required
def task_complete(request, task_id):
  times = Time.objects.filter(task=task_id)
  if len(times) == 0:
    messages.success(request, 'Add time to complete the task!')
    return redirect('task_show', task_id=task_id)
  else:
    task = Task.objects.get(id=task_id)
    task.taskComplete = True
    task.taskCompletedDate = datetime.date.today()
    # for demo, had to set some tasks back in time in new db
    # new_date = date(2020,10,28)
    # task.createdDate = new_date
    # print(task.createdDate)
    task.save()
  return redirect(request.META.get('HTTP_REFERER'))

# --- UN-COMPLETE A TASK ROUTE ---
@login_required
def task_uncomplete(request, task_id):
  task = Task.objects.get(id=task_id)
  if request.user.id == task.creator.user.id:
    if task.taskComplete == True:
      task.taskComplete = False
      task.taskCompletedDate = None
      task.save()
    return redirect(request.META.get('HTTP_REFERER'))

# --- DELETE TASK ROUTE ---
@login_required
def task_delete(request, task_id):
  task = Task.objects.get(id=task_id)
  if task.creator.id == request.user.id:
    task.delete()
  return redirect('tasks')




# NOTES ====================================
# --- ADD NOTES ROUTE TO TASK ---
@login_required
def note_add(request, task_id):
  if request.method == 'POST':
    note = request.POST.get('note')
    task = Task.objects.get(id=task_id)
    creator = Profile.objects.get(id=request.user.id)
    new_note = Note(note=note, task=task, creator=creator)
    new_note.save()
    return redirect('task_show', task_id=task_id)
  # this is in the Task_show page
  return render ('Nothing here yet')

@login_required
def note_edit(request, note_id):
  note = Note.objects.get(id=note_id)
  task_id = note.task.id
  if request.method == 'POST':
    if request.user.id == note.creator.user.id:
      note_form = NoteForm(request.POST, instance=note)
      if note_form.is_valid():
        note_form.save()
        return redirect('task_show', task_id=task_id)
    else:
      return redirect('task_show', task_id=task_id)
  else:
    note_form = NoteForm(instance=note)
  context = {'note' : note, 'note_form': note_form }
  print(note_form)
  return render (request, 'notes/edit.html', context)

@login_required
def note_delete(request, note_id):
  note = Note.objects.get(id=note_id)
  task_id = note.task.id
  note.delete()
  return redirect('task_show', task_id=task_id)    






# PROFILE ====================================
# --- PROFILE SHOW ROUTE ---
@login_required
def profile_show(request, profile_id):
  profile = Profile.objects.get(id=profile_id)
  projects = Project.objects.filter(creator=profile_id)
  tasks = Task.objects.filter(creator=profile_id)
  durations = []
  tasksCompleted = 0
  tags = []
  for task in tasks:
    times = Time.objects.filter(task=task.id)
    for time in times:
      durations.append(time.getDuration())
      tags.append(time.getTags())
    if task.taskComplete == True:
      tasksCompleted += 1
  #  form data
  projectsTotal = len(projects)
  taskTotal = len(tasks)
  timeTotal = sum(durations, datetime.timedelta())
  task_tags = zip(tasks, tags)
  print(task_tags)
  context = {'profile': profile, 'projects': projects, 'tasks': tasks, 'projectsTotal': projectsTotal, 'taskTotal': taskTotal, 'timeTotal': timeTotal, 'tasksCompleted': tasksCompleted, 'tags': tags, 'task_tags': task_tags }
  return render(request, 'profile/show.html', context)

@login_required
# --- PROFILE EDIT ROUTE ---
def profile_edit(request, profile_id):
  profile = Profile.objects.get(id=profile_id)
  if request.method == 'POST':
    if request.user.id == profile.user.id: 
      profile_form = ProfileForm(request.POST, instance=profile)
      if profile_form.is_valid():
        profile_form.save()
        return redirect('profile_show', profile_id=profile_id)
    else:
      return redirect('profile_show', profile_id=profile_id)
  else:
    profile_form = ProfileForm(instance=profile)
  context = { 'profile': profile, 'profile_form': profile_form}
  print(profile_form)
  return render(request, 'profile/edit.html', context)

@login_required
# --- PROFILE DELETE ROUTE ---
def profile_delete(request, profile_id):
  user = User.objects.get(id=profile_id)
  if request.user.id == user.id: 
    user.delete()
  return redirect('/')






# PROJECTS ====================================
# --- SHOW ALL PROJECTS & NEW PROJECT ROUTE ---
@login_required
def projects(request):
  if request.method == 'POST':
    projectName = request.POST.get('project')
    creator = Profile.objects.get(id=request.user.id)
    new_project = Project(projectName=projectName, creator=creator)
    new_project.save()
  projects = Project.objects.filter(creator=request.user.profile)
  project_form = ProjectForm()  
  context = { 'projects': projects, 'project_form': project_form }
  return render(request, 'projects/index.html', context )

# --- PROJECT SHOW ROUTE ---
@login_required
def project_show(request, project_id):
  project = Project.objects.get(id=project_id)
  tasks = Task.objects.filter(project=project_id)
  taskTotal = len(tasks)
  durations = []
  tasksCompleted = 0
  tags = []
  for task in tasks:
    times = Time.objects.filter(task=task.id)
    for time in times:
      durations.append(time.getDuration())
      tags.append(time.getTags())
    if task.taskComplete == True:
      tasksCompleted += 1
  timeTotal = sum(durations, datetime.timedelta())
  task_tags = zip(tasks, tags)
  print(task_tags)
  context = { 'project': project, 'tasks': tasks, 'taskTotal': taskTotal, 'timeTotal': timeTotal, 'tasksCompleted': tasksCompleted, 'tags': tags, 'task_tags': task_tags }
  return render( request, 'projects/show.html', context )

# --- PROJECT SHOW ROUTE ---
@login_required
def project_edit(request, project_id):
  project = Project.objects.get(id=project_id)
  if request.method == 'POST':
    if request.user.id == project.creator.user.id: 
      project_form = ProjectForm(request.POST, instance=project)
      if project_form.is_valid():

main_app/templates/tasks/edit.html
{% extends 'base.html' %}
{% block content %}

<!-- TASK EDIT FORM -->
<form action={% url 'task_edit' task.id %} method="POST">
  {% csrf_token %}
    <div class="columns is-mobile is-centered">
      <div class="column is-half">
        <div class="field">
          <p class="control has-icons-left has-icons-right">
          <p class="field">
            {% if field.errors %}
                <p class="errors">{{ field.errors }}</p>
            {% endif %}
            {{ field.label_tag }}
            <input class="input" {{ task_form.taskName }}
                <p class="control">
                <span class="select" >
                    <label for="project"></label>  
                    <select name="project" >
                    {% for project in projects %}
                        <option value={{ project.id }}> {{ project }}</option>
                    {% endfor %}
                    </select>
                </span></p>

            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        <div class="buttons has-addons is-left">
            <input type="submit" class="button" id="is-green" value="Update">
            <a class="button is-red" id="showTaskDeleteModal">Delete</a><br> 
        </div>
      </p>
    </div>   
</form>

<!-- MODAL FOR DELETE PROFILE -->
<div class="modal" id="deleteTask">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head" id="is-red">
      <button class="delete closeModal" aria-label="close"></button>
    </header>
    <section class="modal-card-body" id="is-background">
      <form action="" method="POST">
        {% csrf_token %}
        <div class="columns is-mobile is-centered">
          <div class="column is-half">
            <div class="field">
                <p class="subtitle">Just checking, you are deleting, {{ task }}</p>
            </div>
          </div>
        </div>
      </form> 
    </section>
      <footer class="modal-card-foot">
      <div class="buttons has-addons is-right">
        <a class="button is-red" href={% url 'task_delete' task.id %}>Yes, Delete</a>
      </div>
    </footer>
  </div>
</div>

{% endblock %}

main_app/templates/tasks/index.html
{% extends 'base.html' %}
{% block content %}

<!-- TASK FORM, FILTERS FOR USER AND TAKES IN INPUT -->
<div class="box is-mobile">
    <form method='POST' action={% url 'tasks' %}>
    {% csrf_token %}    
        <div class="field has-addons">
            <p class="control is-expanded">
                <input class="input is-medium" type="text" name="taskName" placeholder="... enter a task name"></p>
            <p class="control">
                <span class="select is-medium">
                    <label for="project"></label>  
                    <select name="project">
                    {% for project in projects %}
                        <option value={{ project.id }}>{{ project }}</option>
                    {% endfor %}
                    </select>
                </span></p>
            <p class="control">
                <input type="submit" class="button is-medium" id="is-green" value="add task">
                </p>
        </div>
    </form>
</div>

<!-- TASK GROUPINGS BELOW -->
<div class="tile is-ancestor is-mobile">
        <!-- LEFT TILE -->
    <div class="tile is-4 is-parent">
        <div class="tile is-child box">
            <p class="heading">Prior Tasks:</p>
            {% for task in priorTasks %}
                {% if task.taskComplete == True %}
                <div class="card" id="is-complete">
                    <div class="card-content">
                        <p class="card-title is-size-6">{{ task.taskName }} - {{task.createdDate}}</p>
                    </div>
                </div>
                {% endif %}
                {% if task.taskComplete == False %}
                <div class="card" id="is-red-outline">
                    <div class="card-content">
                        <p class="card-title is-size-6">{{ task.taskName }} - {{task.createdDate}}</p>
                    </div>   
                </div>
                {% endif %}    

            {% endfor %}
        </div>
    </div>
    <!-- RIGHT TILE -->
    <div class="tile is-parent">
        <div class="tile is-child box">
        <p class="heading">Tasks for today: &nbsp {% now "SHORT_DATE_FORMAT" %}</p>
        {% for task in tasks %}
            <a href="{% url 'task_show' task.id %}">
                <div class="card">
                    <div class="level">
                        <div class="level-left">
                            <div class="card-content">
                                <p class="card-title is-size-5">{{ task.taskName }} </i></p>
                                <p class="heading">{{ task.project.projectName }}, {{ task.createdDate }}</p>
                            </div>   
                        </div>
                        <div class="level-right">
                            <!-- <a class="button" id="complete"><strong>complete</strong></a> -->
                            
                        </div>  
                    </div>
                </a>
            </div>
        {% empty %}
        <p class="no-info">You have no Tasks yet, add them above </p>  
        {% endfor %}
        </div>
    </div>
</div>





{% endblock %}

main_app/templates/tasks/show.html
{% extends 'base.html' %}
{% block content %}

<!-- TASK TILES -->
<div class="tile is-ancestor">
    <!-- LEFT TILE -->
    <div class="tile is-4 is-parent">
        <div class="tile is-child box">
            <p class="title">{{ task.taskName }} &nbsp 
                <a class="is-tasker-medium-edit-icon"
                    method='POST'
                    href={% url 'task_edit' task.id %}>
                        <i class="fas fa-edit"></i>
                </a></p>
            <a href={% url 'project_show' project.id %}>
                <p>{{ project }}</p>
            </a>
            <p>Completed: {{ task.taskCompletedDate }}</p>
        </div>
    </div>
    <!-- MIDDLE TILE -->
    <div class="tile is-6 is-parent">
        <div class="tile is-child box">
            <div class="level">
            <div class="level-item has-text-centered data-level">
                <div>
                <p class="heading is-green-text">Hours</p>
                <p class="title is-green-text">{{ totalTime }}</p>
                </div>
            </div>
            <div class="level-item has-text-centered data-level">
                <div>
                {% if messages %}
                    <p class="messages no-info">
                        {% for message in messages %}
                        <p class="{{ message.tags }}">{{ message }}</p>
                        {% endfor %}
                    </p>
                {% endif %}
                </div>
            </div>
            </div>
        </div>
    </div>
    <!-- RIGHT TILE -->
    <div class="tile is-parent">
        <div class="tile is-child box">
            <div class="buttons has-addons is-left">
                <button class="button is-fullwidth" id="is-blue">
                    <a method="POST" href={% url 'task_complete' task.id %}>complete</a>
                </button>
                <button class="button is-fullwidth" id="is-red" >
                    <a method="POST" href={% url 'task_uncomplete' task.id %}>uncomplete</a>
                </button>
                <button class="button is-fullwidth" id="is-green">
                    <a method="POST" id="showAddTimeModal">add time</a>
                </button>
            </div>
        </div>
    </div> 
</div>


<!-- NOTES INPUT -->
<div class="box is-mobile">
    <form action={% url 'note_add' task.id %} method='POST'>
    {% csrf_token %}    
        <div class="field has-addons">
            <p class="control is-expanded">
                <input class="input is-small" type="text" name="note" placeholder="... enter a note"></p>

            <p class="control">
                <input type="submit" class="button is-small" id="is-green" value="add note"></p>
        </div>
    </form>
</div>


<div class="tile is-ancestor">
    <!-- LEFT TILE -->
    <div class="tile is-10 is-parent">
        <div class="tile is-child box">
            <!-- BULMA MEDIA OBJECT NOTES DISPLAY -->
            <p class="heading">Notes</p>
            {% for note in notes %}
            <article class="media">
                <div class="media-content">
                    <div class="content">
                    <p>
                        <strong>{{ note.creator.name }}</strong><small> - {{ note.noteCreatedDate }}</small>
                        <br>
                        <small>{{ note.note|urlize }}</small></p>
                    
                    </div>
                    <nav class="level is-mobile">
                        <div class="level-left">
                            <a class="level-item" method="POST" href={% url 'note_edit' note.id %}>
                                <span class="is-tasker-small-edit-icon">
                                <i class="fas fa-edit"></i></span>
                            </a>
                            <a class="level-item" method="DELETE" href={% url 'note_delete' note.id %}>
                                <span class="is-tasker-small-delete-icon">
                                <i class="fas fa-trash"></i></span>      
                            </a>
                        </div>
                    </nav>
                </div>
            </article>
            {% empty %}
            <p>Add Notes to Tasks for reference </p>        
            {% endfor %} 
        </div>
    </div>

    <!-- RIGHT TILE -->
    <div class="tile is-parent">
        <div class="tile is-child box">
            <p class="heading">Times</p>
            <p class="subtitle is-5">
            {% for item1, item2 in timeDates %}
                <a class=" is-small" method="POST" href={% url 'time_edit' item1.id %}>
                <span class="tag is-normal" id="is-blue">{{ item2 }}-{{ item1 }} &nbsp &nbsp
                    <i class= "fas fa-edit" ></i>
                </span></a>
                <br>
            {% empty %}
            <p>Add time to tasks. </p>        
            {% endfor %} </p>
            </div>
        </div>
    </div> 
</div>

<!-- MODAL FOR TIME INPUTS -->
<div class="modal" id="addTime">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head" id="is-green">
      <button class="delete closeModal" aria-label="close"></button>
    </header>
    <section class="modal-card-body" id="is-background">
      <form action={% url 'time_add' %} method="POST">
        {% csrf_token %}
        <div class="columns is-mobile is-centered">
          <div class="column is-half">
            <div class="field">
                <p class="control has-icons-left has-icons-right">
                <p class="field">
                    <label for="id_date"></label>
                    <input type="date" name="date" required id="id_date" class="input"></p>
                
                <p class="field">
                    <label for="id_startTime"></label>
                    <input type="time" name="startTime" required id="id_startTime" class="input"></p>
                
                <p class="field">
                    <label for="id_endTime"></label>
                    <input type="time" name="endTime" required id="id_endTime" class="input"></p>
                
                <p class="field">
                    <label for="id_tags"></label>
                    <input type="text" name="tags" required id="id_tags" class="input" placeholder="...enter a tag to organize your time"></p>
                
                <!-- APPLIES A HIDDEN INPUT TO PUSH TASK ID INTO REQUEST DOT POST -->
                <p class="field">
                    <label for="id_task"></label>
                    <input class="input" type="hidden" name="task" value={{ task.id }}>
                <br>
                <button class="button" id="is-green" type="submit">add time</button>
            </div>
          </div>
        </div>
      </form> 
    </section>
  </div>
</div>
{% endblock %}